{{- range .Values.extraServices }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "homelab-chart.fullname" $ }}-{{ .name }}
  labels:
    {{- include "homelab-chart.labels" $ | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .type }}
  {{- with .loadBalancerClass }}
  loadBalancerClass: {{ . }}
  {{- end }}
  ports:
    {{- range .ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort | default .port }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "homelab-chart.selectorLabels" $ | nindent 4 }}
{{- end }}
