{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "homelab-chart.fullname" . }}
  labels:
    {{- include "homelab-chart.labels" . | nindent 4 }}
    release: {{ .Values.serviceMonitor.release }}
  {{- with .Values.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "homelab-chart.selectorLabels" . | nindent 6 }}
  endpoints:
    {{- range .Values.serviceMonitor.endpoints }}
    - port: {{ .port | quote }}
      {{- with .path }}
      path: {{ . | quote }}
      {{- end }}
      {{- with .interval }}
      interval: {{ . | quote }}
      {{- end }}
      {{- with .scrapeTimeout }}
      scrapeTimeout: {{ . | quote }}
      {{- end }}
    {{- end }}
{{- end }}
